### ISSUE TITLE
Include rspec as a default gem

### ISSUE THREAD

**Issue by mount986** [jruby/docker-jruby#64]
I use Rubymine and I can't use the base jruby image to run my rspec tests in the IDE because rspec is not included.  Minitest is included, and rspec has double the downloads on rubygems.org.  It would be nice if I didn't have to create my own image just to run rspec.

**Comment by cpuguy83** [comment]
Sorry, this doesn't seem right.
The only included gems are those that come with jruby an `bundler rake net-telnet xmlrpc`... all but bundler are included because they were left out of jruby at one point and expected to be there... I'm not sure if they got added back the the actual releases.

How come including `rpsec` as a test dependency in your bundler config?

**Comment by mount986** [comment]
see #65 as to why I can't just include rspec in my bundler config.  However, I recognize this was a long shot, but I figured it worth having the discussion.  I wouldn't have asked, except that minitest is included by default. (I recently checked, and it's also included in the ruby image, so I assume that's why)

**Comment by cpuguy83** [comment]
Only way minitest is included is if it's part of the jruby tarball or a dependency of one of the explicitly installed gems.

Thanks!
